version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: pramaan-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: pramaan-attendance
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - pramaan-network

  redis:
    image: redis:7-alpine
    container_name: pramaan-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis123
    volumes:
      - redis_data:/data
    networks:
      - pramaan-network

  backend:
    build: .
    container_name: pramaan-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/pramaan-attendance?authSource=admin
      REDIS_URL: redis://:redis123@redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./certificates:/app/certificates
      - ./uploads:/app/uploads
    networks:
      - pramaan-network

  nginx:
    image: nginx:alpine
    container_name: pramaan-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - pramaan-network

volumes:
  mongodb_data:
  redis_data:

networks:
  pramaan-network:
    driver: bridge
